# This file contains all possible places where the robot can go.

places: {
    '1.3.C12_tv': {
        id: '1.3.C12_tv',
        name: tv_lab,
        x: 1.334,
        y: 0.785,
        z: 0.0,
        theta: 1.562
    },

    '1.3.C12_door': {
        id: '1.3.C12_door',
        name: door_lab,
        x: 2.4,
        y: -1.1,
        z: 0.0,
        theta: 0.0
    },

    '1.3.C12_charger': {
        id: '1.3.C12_charger',
        name: charger_lab,
        x: 2.8,
        y: -2.34,
        z: 0.0,
        theta: 0.0
    },

    '1.3.C12_develop': {
        id: '1.3.C12_develop',
        name: develop_lab,
        x: -0.3,
        y: 0.3385,
        z: 0.0,
        theta: 0.0
    },
}


