# This file contains all the possible places where the robot can go.

# Place format:
# place_name:
#    x:
#    y:
#    z:
#    w:
patrolling_route:
# Short patrol route inside lab 1.3.12 at roboticslab
#- '1.3.C12_centre'
#- '1.3.C12_maggie'
#- '1.3.C12_inigo'
#- '1.3.C12_charger'
# Short patrol route to cover half roboticslab corridor
- '1.3.C12'
- '1.3.C12_charger'
- '1.3.C12_centre'
- '1.3.C09'
- '1.3.C02'
- '1.3.C14'
# Patrol route to cover the whole roboticslab corridor
#- '1.3.A_entrance_a'
#- '1.3.C14'
#- '1.3.C12'
#- '1.3.A_entrance_a'
#- '1.3.C12'
#- '1.3.A_entrance_a'
#- '1.3.C14'
#- '1.3.C12'
#- '1.3.A_entrance_a'
#- '1.3.C12'
#- '1.3.A_entrance_a'
#- '1.3.C14'
#- '1.3.C12'
#- '1.3.A_entrance_a'
#- '1.3.C12'
#- '1.3.A_entrance_a'
#- '1.3.C14'
#- '1.3.C12'
#- '1.3.A_entrance_a'
#- '1.3.C12'
# The patrolling route is repeated 4 times
# - '1.3.C12'
# - '1.3.C14'
# - '1.3.AB_map'
# - '1.3.A_entrance_a'
# - '1.3.AB_stairwell'
# - '1.3.BC_stairwell'
# - '1.3.CD_stairwell_1'
# - '1.3.CD_stairwell_2'
# - '1.3.D_entrance_d'
# - '1.3.CD_empty_space'
# - '1.3.C12'
# - '1.3.C14'
# - '1.3.AB_map'
# - '1.3.A_entrance_a'
# - '1.3.AB_stairwell'
# - '1.3.BC_stairwell'
# - '1.3.CD_stairwell_1'
# - '1.3.CD_stairwell_2'
# - '1.3.D_entrance_d'
# - '1.3.CD_empty_space'
# - '1.3.C12'
# - '1.3.C14'
# - '1.3.AB_map'
# - '1.3.A_entrance_a'
# - '1.3.AB_stairwell'
# - '1.3.BC_stairwell'
# - '1.3.CD_stairwell_1'
# - '1.3.CD_stairwell_2'
# - '1.3.D_entrance_d'
# - '1.3.CD_empty_space'
# - '1.3.C12'
# - '1.3.C14'
# - '1.3.AB_map'
# - '1.3.A_entrance_a'
# - '1.3.AB_stairwell'
# - '1.3.BC_stairwell'
# - '1.3.CD_stairwell_1'
# - '1.3.CD_stairwell_2'
# - '1.3.D_entrance_d'
# - '1.3.CD_empty_space'
