# This file contains all the possible places where the robot can go.

patrolling_route:
- '1.3.A_entrance_a'
- '1.3.C14'
- '1.3.C12'
- '1.3.A_entrance_a'
- '1.3.C12'
- '1.3.A_entrance_a'
- '1.3.C14'
- '1.3.C12'
- '1.3.A_entrance_a'
- '1.3.C12'
- '1.3.A_entrance_a'
- '1.3.C14'
- '1.3.C12'
- '1.3.A_entrance_a'
- '1.3.C12'
- '1.3.A_entrance_a'
- '1.3.C14'
- '1.3.C12'
- '1.3.A_entrance_a'
- '1.3.C12'
